Repository CodeYourFuture/directory-of-services, pull requests merged in 2018-08, with the labels that each got.

#196 Make area and borough field input data more consistent
  script/data.js
  script/flattenedFinalData.json
  script/newData.json
Labels: Review Me

#157 added some descriptions for package.json scripts and stopped git trak…
  backend/.env
  backend/README.md
  frontend/.env
Labels: Reviewed - Ready to Merge

#204 Increase width of card detail org component to avoid scrolling to read info
  frontend/src/Components/Organisation/edit-org.css
  frontend/src/Components/Organisation/index.css
  frontend/src/Components/Organisation/single-org.css
Labels: Review Me

#203 Create test for get API endpoints route
  backend/.eslintrc
  backend/package.json
  backend/src/controllers/get_controller.js
  backend/test/api_spec.js
  backend/yarn.lock
Labels: Review Me

#192 fixed select active class issue at sidebar
  frontend/src/Components/SideBar/index.js
  frontend/src/actions/loginActions.js
Labels: Review Me

#169 updated edit, add an organisation, reset, forgot and getfilteredbranc…
  frontend/src/Components/Organisation/AddOrganisation.js
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Users/forgot-password/Reset.js
  frontend/src/Components/Users/forgot-password/index.js
  frontend/src/actions/postData.js
Labels: Review Me, Reviewed - Ready to Merge

#177 Created initial test to Organisation, addOrganisation, editOrganisati…
  frontend/src/_test_/AddOrganisation.test.js
  frontend/src/_test_/App.test.js
  frontend/src/_test_/EditOrganisations.test.js
  frontend/src/_test_/Organisation.test.js
  frontend/src/_test_/OrganisationCard.test.js
  frontend/src/_test_/OrganisationForm.test.js
  frontend/src/_test_/Search.test.js
  frontend/src/_test_/SingleOrganisation.test.js
Labels: Review Me

#179 created initial test to forgot password, reset password, signup field…
  frontend/src/_test_/ForgotPassword.test.js
  frontend/src/_test_/Reset.test.js
  frontend/src/_test_/SignUpFields.test.js
  frontend/src/_test_/SignUpForm.test.js
Labels: Review Me

#185 moved logo to same as topNav height
  backend/src/routes/users.js
  frontend/src/Components/SideBar/index.js
  frontend/src/Components/SideBar/side-bar.css
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/UsersListTable.js
  frontend/src/actions/loginActions.js
Labels: Review Me

#180 Created initial test to Categories, HomePage, HomeSearch, LandingPage…
  frontend/src/_test_/Categories.test.js
  frontend/src/_test_/HomePage.test.js
  frontend/src/_test_/HomeSearch.test.js
  frontend/src/_test_/LandingPage.test.js
  frontend/src/_test_/Login.test.js
  frontend/src/_test_/LoginForm.test.js
Labels: Review Me

#181 Created initial test to SideBar, Spinner and TopNav components
  frontend/src/_test_/SideBar.test.js
  frontend/src/_test_/Spinner.test.js
  frontend/src/_test_/TopNav.test.js
  frontend/yarn.lock
  package.json
  yarn.lock
Labels: Review Me

#188 Connect delete branch api to client
  backend/src/routes/api.js
  frontend/src/Components/Organisation/SingleOrganisation.js
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/users.css
  frontend/src/actions/postData.js
Labels: Reviewed - Ready to Merge

#202 Add category to organisationCards in homeSearch component
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/Organisation/OrganisationCard.js
  frontend/src/Components/Organisation/index.js
Labels: Reviewed - Ready to Merge

#201 Update list of borough and area
  frontend/src/Components/Organisation/OrganisationForm.js
  frontend/src/Data/Boroughs.json
Labels: Review Me

#190 refactored HomeSearch Component
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/HomePage/SearchForm.js
  frontend/src/Components/HomePage/homePageHelper.js
  frontend/src/Components/HomePage/style.js
Labels: Reviewed - Ready to Merge

#189 Use async await try catch functions with all cation functions
  frontend/src/Components/TopNav/index.js
  frontend/src/Components/Users/UserProfilePage/index.js
  frontend/src/Components/Users/UsersMenu.js
  frontend/src/actions/getApiData.js
  frontend/src/actions/loginActions.js
  frontend/src/actions/postData.js
  frontend/src/helpers.js
Labels: Review Me

#194 Created flashMessagesNotification component to fix notification libra…
  frontend/src/Components/FlashMessages/index.js
  frontend/src/Components/FlashMessages/style.css
  frontend/src/Components/HomePage/index.js
  frontend/src/Components/LandingPage/index.js
  frontend/src/Components/LandingPage/landing-page.css
  frontend/src/Components/LoginForm/index.js
  frontend/src/Components/TopNav/index.js
  frontend/src/reducers/flashMessages.js
Labels: Review Me

#191 refactored edit an organisation component and remove unused JSON data…
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Organisation/index.js
  frontend/src/Components/Organisation/orgHelpers.js
  frontend/src/Components/Organisation/org_data.js
  frontend/src/Components/Organisation/org_data.json
Labels: Reviewed - Ready to Merge

#195 used put request with edit an organisation and update user instead of…
  backend/src/routes/api.js
  frontend/src/actions/postData.js
Labels: Review Me

#197 Increase width of edit org component
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Organisation/OrganisationForm.js
Labels: Reviewed - Ready to Merge

#205 Udpate db
  backend/data/data.json
  script/flattenedFinalData.json
  script/newData.json
Labels: Review Me

#193 Catch signup error with try-catch and use async-awiat in a right way
  backend/src/routes/users.js
Labels: Review Me

#206 Edit button enabled in home component
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/HomePage/index.js
Labels: Review Me

#208 Fix user DropMenu styling
  frontend/src/Components/Users/user-drop-down.css
Labels: Review Me

#210 Make delete an organisation button visible only to admin
  frontend/src/Components/Organisation/SingleOrganisation.js
Labels: Review Me

#212 Fix style for Edit and Detail button in HomeSearch component
  frontend/src/Components/HomePage/HomePage.css
  frontend/src/Components/HomePage/HomeSearch.js
Labels: Reviewed - Ready to Merge

#213 Cleaned the console errors at edit, add and organisationForm components
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Organisation/OrganisationForm.js
Labels: Review Me

#217 Resize of single org detail component
  frontend/src/Components/Organisation/single-org.css
Labels: Review Me

#211 Cleaned all console errors accept edit, add and organisationForm comp…
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/LoginForm/index.js
  frontend/src/Components/Organisation/AddOrganisation.js
  frontend/src/Components/Organisation/SingleOrganisation.js
  frontend/src/Components/Organisation/index.js
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/UsersListTable.js
Labels: Review Me

#215 Fix spelling error and Add One more expect to check whether the data is array
  backend/package.json
  backend/test/api_spec.js
Labels: Reviewed - Ready to Merge

#222 Removed package-lock.json from front-end and main directory to fix se…
  frontend/package-lock.json
  package-lock.json
Labels: Review Me

#216 Allow admin to access list of users && display current user on user profile list
  frontend/src/Components/TopNav/index.js
  frontend/src/Components/Users/UserDropDown.js
  frontend/src/Components/Users/UserProfilePage/index.js
  frontend/src/Components/Users/index.js
  frontend/src/Components/Users/user-drop-down.css
  frontend/src/Routes.js
Labels: Review Me

#220 Created test for getController API functions
  backend/test/get_controller_spec.js
Labels: Review Me

#218 Write test for post API controller
  backend/package.json
  backend/src/routes/api.js
  backend/test/api_spec.js
Labels: Review Me

#221 Create test for api post controller
  backend/src/controllers/get_controller.js
  backend/src/controllers/post_controller.js
  backend/src/routes/api.js
  backend/test/post_controller_spec.js
  frontend/src/actions/postData.js
Labels: Review Me

#224 Create test for users api
  backend/src/routes/users.js
  backend/test/users_api_spec.js
Labels: Review Me

#227 fixed flattenData function issue
  backend/.eslintrc
  backend/library/helpers.js
  backend/src/controllers/get_controller.js
Labels: Review Me
