Repository CodeYourFuture/directory-of-services, pull requests merged in 2018-07, with the labels that each got.

#159 Handle days info in FE
  frontend/src/Components/Organisation/OrganisationForm.js
  frontend/src/Components/Organisation/PaperOrg.css
  frontend/src/Components/Organisation/SingleOrganisation.js
  frontend/src/Components/Organisation/edit-org.css
Labels: Reviewed - Ready to Merge

#162 Improve search functionality in home search
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/Organisation/search.css
Labels: Reviewed - Ready to Merge

#164 Handle case where day field info is Monday, Tuesday, ... to Friday
  frontend/src/Components/Organisation/index.js
Labels: Reviewed - Ready to Merge

#165 Fix edit orgs hiding card issue
  backend/src/routes/api.js
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Organisation/OrganisationCard.js
  frontend/src/Components/Organisation/SingleOrganisation.js
  frontend/src/Components/Organisation/index.js
Labels: Reviewed - Ready to Merge

#171 Fix duplication orgs issue
  backend/src/controllers/postInitialData.js
  script/data.js
Labels: Review Me, Reviewed - Ready to Merge

#175 cleaned some of components console errors
  frontend/src/Components/Organisation/OrganisationForm.js
  frontend/src/Components/Organisation/Search.js
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/UsersListTable.js
  frontend/src/Data/Boroughs.json
Labels: Review Me, Reviewed - Ready to Merge

#174 removed listOfCategories, listOfBoroughs and listOfAreas from redux c…
  frontend/src/Components/HomePage/index.js
  frontend/src/Components/TopNav/index.js
  frontend/src/actions/getApiData.js
  frontend/src/actions/types.js
  frontend/src/reducers/index.js
  frontend/src/reducers/storeApiData.js
Labels: Review Me, Reviewed - Ready to Merge

#167 updated service and process fields at organisation card to be replace…
  frontend/src/Components/Organisation/OrganisationCard.js
Labels: Reviewed - Ready to Merge

#178 created initial test to UsersPag, AddUser, UsersTable, Notification, …
  frontend/package.json
  frontend/src/Components/Users/AddUser.js
  frontend/src/Components/Users/UsersTableHead.js
  frontend/src/_test_/AddUser.test.js
  frontend/src/_test_/Notification.test.js
  frontend/src/_test_/UserDropDown.test.js
  frontend/src/_test_/UsersListTable.test.js
  frontend/src/_test_/UsersMenu.test.js
  frontend/src/_test_/UsersPage.test.js
  frontend/src/_test_/UsersTableHead.test.js
  frontend/yarn.lock
Labels: Review Me

#170 Script: Update day field
  script/data.js
  script/flattenedFinalData.json
  script/newData.json
Labels: Reviewed - Ready to Merge

#186 Add ability to delete org
  backend/db/migrations/20180308173243_create_all_tables.js
  backend/src/controllers/post_controller.js
  backend/src/routes/api.js
Labels: Review Me

#172 Create user profile component and unique route for admin
  backend/src/routes/users.js
  frontend/src/Components/HomePage/HomeSearch.js
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/UserDropDown.js
  frontend/src/Components/Users/UserProfilePage/Userprofile.css
  frontend/src/Components/Users/UserProfilePage/index.js
  frontend/src/Components/Users/UsersMenu.js
  frontend/src/Components/Users/index.js
  frontend/src/Routes.js
Labels: Reviewed - Ready to Merge

#176 Add ability to delete user
  backend/src/routes/users.js
  frontend/src/Components/Users/Notification.js
  frontend/src/Components/Users/UsersListTable.js
  frontend/src/actions/postData.js
Labels: Review Me, Reviewed - Ready to Merge

#182 Add categories list from Data/Categories.json to TopNav
  frontend/src/Components/TopNav/index.js
Labels: Review Me, Reviewed - Ready to Merge

#183 Improve multiselection of category when adding new org
  frontend/src/Components/Organisation/AddOrganisation.js
Labels: Review Me, Reviewed - Ready to Merge

#173 Fix issue that cause an organisation to disappear when editing
  frontend/src/Components/Organisation/EditOrganisation.js
Labels: Review Me

#166 Allow only admin edit and add organisation
  backend/src/routes/users.js
  frontend/src/Components/Organisation/EditOrganisation.js
  frontend/src/Components/Organisation/OrganisationCard.js
  frontend/src/Components/Organisation/SingleOrganisation.js
  frontend/src/Components/Organisation/index.js
  frontend/src/Components/Organisation/single-org.css
  frontend/src/Components/SideBar/index.js
  frontend/src/Components/TopNav/index.js
Labels: Review Me, Reviewed - Ready to Merge
